export const INITIALIZE="INITIALIZE";
export const TOGGLE_LIKE="TOGGLE_LIKE"
export const MOST_LIKED="MOST_LIKED";
export const MOST_COMMENTED="MOST_COMMENTED";
export const SEARCH_CATEGORY="SEARCH_CATEGORY";
export const POST_COMMENT="POST_COMMENT";
export const DELETE_COMMENT="DELETE_COMMENT";
export const TOGGLE_MODAL="TOGGLE_MODAL";